/*******************************************************************************
 * EMF Specific API of the policy.dsod pattern
 * Generated by EMF-IncQuery
 *******************************************************************************/

package patternmatchers.policy;

import java.util.Collection;

import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseGeneratedMatcher;
import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseMatcherFactory;
import org.eclipse.viatra2.emf.incquery.runtime.api.IPatternSignature;
import org.eclipse.viatra2.emf.incquery.runtime.api.IMatcherFactory;
import org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher;
import org.eclipse.viatra2.emf.incquery.runtime.exception.IncQueryRuntimeException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.ReteEngine;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;

import signatures.policy.DsodSignature;

/**
 * Generated domain-specific pattern matcher API of of the policy.dsod pattern.
 * Please instantiate using the static field FACTORY.
 */
@SuppressWarnings("unused")
public class DsodMatcher extends BaseGeneratedMatcher<DsodSignature> implements IncQueryMatcher<DsodSignature>{

	public final static IMatcherFactory<DsodSignature,DsodMatcher> FACTORY = new Factory();
	public static class Factory extends BaseMatcherFactory<DsodSignature,DsodMatcher> {
			@Override
			public DsodMatcher instantiate(ReteEngine<String> reteEngine) throws IncQueryRuntimeException {
				return new DsodMatcher(reteEngine);
			}
			@Override
			public String getPatternName() {
				return "policy.dsod";
			}
		} 
			
	
	/** 
	 * Returns the set of all pattern matches given some fixed parameters.
	 * @param USER the fixed value of pattern parameter USER, or null if not bound.
	 * @param ROLEA the fixed value of pattern parameter ROLEA, or null if not bound.
	 * @param ROLEB the fixed value of pattern parameter ROLEB, or null if not bound.
	 * @return matches represented as an array containing the values of each parameter.
	 */
	public Collection<Object[]> getAllMatchesAsArray(Object USER, Object ROLEA, Object ROLEB) {
		return getAllMatchesAsArray(new Object[] {USER, ROLEA, ROLEB});
	}
	
	/** 
	 * Returns the set of all pattern matches given some fixed parameters.
	 * @param USER the fixed value of pattern parameter USER, or null if not bound.
	 * @param ROLEA the fixed value of pattern parameter ROLEA, or null if not bound.
	 * @param ROLEB the fixed value of pattern parameter ROLEB, or null if not bound.
	 * @return matches represented as a DsodSignature object.
	 */
	public Collection<DsodSignature> getAllMatchesAsSignature(Object USER, Object ROLEA, Object ROLEB) {
		return getAllMatchesAsSignature(new Object[] {USER, ROLEA, ROLEB});
	}

	/** 
	 * Returns an arbitrary pattern match given some fixed parameters.
	 * Neither determinism nor randomness of selection is guaranteed.
	 * @param USER the fixed value of pattern parameter USER, or null if not bound.
	 * @param ROLEA the fixed value of pattern parameter ROLEA, or null if not bound.
	 * @param ROLEB the fixed value of pattern parameter ROLEB, or null if not bound.
	 * @return a match represented as an array containing the values of each parameter, or null if no match is found.
	 */
	public Object[] getOneMatchAsArray(Object USER, Object ROLEA, Object ROLEB) {
		return getOneMatchAsArray(new Object[] {USER, ROLEA, ROLEB});
	}
	
	/** 
	 * Returns an arbitrary pattern match given some fixed parameters.
	 * Neither determinism nor randomness of selection is guaranteed.
	 * @param USER the fixed value of pattern parameter USER, or null if not bound.
	 * @param ROLEA the fixed value of pattern parameter ROLEA, or null if not bound.
	 * @param ROLEB the fixed value of pattern parameter ROLEB, or null if not bound.
	 * @return a match represented as a DsodSignature object, or null if no match is found.
	 */
	public DsodSignature getOneMatchAsSignature(Object USER, Object ROLEA, Object ROLEB) {
		return getOneMatchAsSignature(new Object[] {USER, ROLEA, ROLEB});
	}
	
	/**
	 * Indicates whether the given combination of specified pattern parameters constitute a valid pattern match,
	 * 	under any possible substitution of the unspecified parameters.
	 * @param USER the fixed value of pattern parameter USER, or null if not bound.
	 * @param ROLEA the fixed value of pattern parameter ROLEA, or null if not bound.
	 * @param ROLEB the fixed value of pattern parameter ROLEB, or null if not bound.
	 * @return true if the input is a valid (partial) match of the pattern.
	 */
	public boolean hasMatch(Object USER, Object ROLEA, Object ROLEB) {
		return hasMatch(new Object[] {USER, ROLEA, ROLEB});
	}
	
	/** 
	 * Returns the number of all pattern matches given some fixed parameters.
	 * @param USER the fixed value of pattern parameter USER, or null if not bound.
	 * @param ROLEA the fixed value of pattern parameter ROLEA, or null if not bound.
	 * @param ROLEB the fixed value of pattern parameter ROLEB, or null if not bound.
	 * @return the number of pattern matches found.
	 */	
	public int countMatches(Object USER, Object ROLEA, Object ROLEB) {
		return countMatches(new Object[] {USER, ROLEA, ROLEB});
	}
	


	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#getPatternName()
	 */
	@Override
	public String getPatternName() {
		return "policy.dsod";
	}

	private static final String[] paramNames = new String[] {"USER", "ROLEA", "ROLEB"};
	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#getParameterNames()
	 */
	@Override
	public String[] getParameterNames() {
		return paramNames;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseGeneratedMatcher#tupleToSignature(org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple)
	 */
	@Override
	protected DsodSignature tupleToSignature(Tuple t) {
		return new DsodSignature(t.get(0), t.get(1), t.get(2));
	}
	
	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#arrayToSignature(java.lang.Object[])
	 */
	@Override
	public DsodSignature arrayToSignature(Object[] signature) {
		return new DsodSignature(signature[0], signature[1], signature[2]);
	}	
	
	private DsodMatcher(ReteEngine<String> engine) throws IncQueryRuntimeException {
		super(engine, "policy.dsod");
	}
		
}
