/*******************************************************************************
 * EMF Specific API of the policy.userActivatedRoleRule pattern
 * Generated by EMF-IncQuery
 *******************************************************************************/

package patternmatchers.policy;

import java.util.Collection;

import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseGeneratedMatcher;
import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseMatcherFactory;
import org.eclipse.viatra2.emf.incquery.runtime.api.IPatternSignature;
import org.eclipse.viatra2.emf.incquery.runtime.api.IMatcherFactory;
import org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher;
import org.eclipse.viatra2.emf.incquery.runtime.exception.IncQueryRuntimeException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.ReteEngine;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;

import signatures.policy.UserActivatedRoleRuleSignature;

/**
 * Generated domain-specific pattern matcher API of of the policy.userActivatedRoleRule pattern.
 * Please instantiate using the static field FACTORY.
 */
@SuppressWarnings("unused")
public class UserActivatedRoleRuleMatcher extends BaseGeneratedMatcher<UserActivatedRoleRuleSignature> implements IncQueryMatcher<UserActivatedRoleRuleSignature>{

	public final static IMatcherFactory<UserActivatedRoleRuleSignature,UserActivatedRoleRuleMatcher> FACTORY = new Factory();
	public static class Factory extends BaseMatcherFactory<UserActivatedRoleRuleSignature,UserActivatedRoleRuleMatcher> {
			@Override
			public UserActivatedRoleRuleMatcher instantiate(ReteEngine<String> reteEngine) throws IncQueryRuntimeException {
				return new UserActivatedRoleRuleMatcher(reteEngine);
			}
			@Override
			public String getPatternName() {
				return "policy.userActivatedRoleRule";
			}
		} 
			
	
	/** 
	 * Returns the set of all pattern matches given some fixed parameters.
	 * @param USER the fixed value of pattern parameter USER, or null if not bound.
	 * @param ROLE the fixed value of pattern parameter ROLE, or null if not bound.
	 * @param OPERATION the fixed value of pattern parameter OPERATION, or null if not bound.
	 * @param OBJECT the fixed value of pattern parameter OBJECT, or null if not bound.
	 * @return matches represented as an array containing the values of each parameter.
	 */
	public Collection<Object[]> getAllMatchesAsArray(Object USER, Object ROLE, Object OPERATION, Object OBJECT) {
		return getAllMatchesAsArray(new Object[] {USER, ROLE, OPERATION, OBJECT});
	}
	
	/** 
	 * Returns the set of all pattern matches given some fixed parameters.
	 * @param USER the fixed value of pattern parameter USER, or null if not bound.
	 * @param ROLE the fixed value of pattern parameter ROLE, or null if not bound.
	 * @param OPERATION the fixed value of pattern parameter OPERATION, or null if not bound.
	 * @param OBJECT the fixed value of pattern parameter OBJECT, or null if not bound.
	 * @return matches represented as a UserActivatedRoleRuleSignature object.
	 */
	public Collection<UserActivatedRoleRuleSignature> getAllMatchesAsSignature(Object USER, Object ROLE, Object OPERATION, Object OBJECT) {
		return getAllMatchesAsSignature(new Object[] {USER, ROLE, OPERATION, OBJECT});
	}

	/** 
	 * Returns an arbitrary pattern match given some fixed parameters.
	 * Neither determinism nor randomness of selection is guaranteed.
	 * @param USER the fixed value of pattern parameter USER, or null if not bound.
	 * @param ROLE the fixed value of pattern parameter ROLE, or null if not bound.
	 * @param OPERATION the fixed value of pattern parameter OPERATION, or null if not bound.
	 * @param OBJECT the fixed value of pattern parameter OBJECT, or null if not bound.
	 * @return a match represented as an array containing the values of each parameter, or null if no match is found.
	 */
	public Object[] getOneMatchAsArray(Object USER, Object ROLE, Object OPERATION, Object OBJECT) {
		return getOneMatchAsArray(new Object[] {USER, ROLE, OPERATION, OBJECT});
	}
	
	/** 
	 * Returns an arbitrary pattern match given some fixed parameters.
	 * Neither determinism nor randomness of selection is guaranteed.
	 * @param USER the fixed value of pattern parameter USER, or null if not bound.
	 * @param ROLE the fixed value of pattern parameter ROLE, or null if not bound.
	 * @param OPERATION the fixed value of pattern parameter OPERATION, or null if not bound.
	 * @param OBJECT the fixed value of pattern parameter OBJECT, or null if not bound.
	 * @return a match represented as a UserActivatedRoleRuleSignature object, or null if no match is found.
	 */
	public UserActivatedRoleRuleSignature getOneMatchAsSignature(Object USER, Object ROLE, Object OPERATION, Object OBJECT) {
		return getOneMatchAsSignature(new Object[] {USER, ROLE, OPERATION, OBJECT});
	}
	
	/**
	 * Indicates whether the given combination of specified pattern parameters constitute a valid pattern match,
	 * 	under any possible substitution of the unspecified parameters.
	 * @param USER the fixed value of pattern parameter USER, or null if not bound.
	 * @param ROLE the fixed value of pattern parameter ROLE, or null if not bound.
	 * @param OPERATION the fixed value of pattern parameter OPERATION, or null if not bound.
	 * @param OBJECT the fixed value of pattern parameter OBJECT, or null if not bound.
	 * @return true if the input is a valid (partial) match of the pattern.
	 */
	public boolean hasMatch(Object USER, Object ROLE, Object OPERATION, Object OBJECT) {
		return hasMatch(new Object[] {USER, ROLE, OPERATION, OBJECT});
	}
	
	/** 
	 * Returns the number of all pattern matches given some fixed parameters.
	 * @param USER the fixed value of pattern parameter USER, or null if not bound.
	 * @param ROLE the fixed value of pattern parameter ROLE, or null if not bound.
	 * @param OPERATION the fixed value of pattern parameter OPERATION, or null if not bound.
	 * @param OBJECT the fixed value of pattern parameter OBJECT, or null if not bound.
	 * @return the number of pattern matches found.
	 */	
	public int countMatches(Object USER, Object ROLE, Object OPERATION, Object OBJECT) {
		return countMatches(new Object[] {USER, ROLE, OPERATION, OBJECT});
	}
	


	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#getPatternName()
	 */
	@Override
	public String getPatternName() {
		return "policy.userActivatedRoleRule";
	}

	private static final String[] paramNames = new String[] {"USER", "ROLE", "OPERATION", "OBJECT"};
	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#getParameterNames()
	 */
	@Override
	public String[] getParameterNames() {
		return paramNames;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseGeneratedMatcher#tupleToSignature(org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple)
	 */
	@Override
	protected UserActivatedRoleRuleSignature tupleToSignature(Tuple t) {
		return new UserActivatedRoleRuleSignature(t.get(0), t.get(1), t.get(2), t.get(3));
	}
	
	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#arrayToSignature(java.lang.Object[])
	 */
	@Override
	public UserActivatedRoleRuleSignature arrayToSignature(Object[] signature) {
		return new UserActivatedRoleRuleSignature(signature[0], signature[1], signature[2], signature[3]);
	}	
	
	private UserActivatedRoleRuleMatcher(ReteEngine<String> engine) throws IncQueryRuntimeException {
		super(engine, "policy.userActivatedRoleRule");
	}
		
}
