/*******************************************************************************
 * Pattern signature of the policy.dsod pattern
 * Generated by EMF-IncQuery
 *******************************************************************************/

package signatures.policy;

import java.util.Arrays;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.viatra2.emf.incquery.runtime.api.IPatternSignature;
import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BasePatternSignature;

/**
 * Pattern-specific signature object of the policy.dsod pattern.
 * Class fields correspond to parameters of the pattern. Fields with value null are considered unassigned.
 * Each instance is a (possibly partial) substitution of pattern parameters, 
 * usable e.g. to represent a match of the pattern in the result of a query, 
 * or to specify the bound (fixed) input parameters when issuing a query.
 */
@SuppressWarnings("unused")
public final class DsodSignature extends BasePatternSignature implements IPatternSignature {

	// constructor
	public DsodSignature(Object USER, Object ROLEA, Object ROLEB) {
		this.fUSER = USER;
		this.fROLEA = ROLEA;
		this.fROLEB = ROLEB;	
	}

	//private attributes
	private Object fUSER;
	private Object fROLEA;
	private Object fROLEB;
	
	// getter methods
	/** Returns the value of the parameter with the given name, or null if name is invalid. */
	@Override
	public Object get(String parameterName) {
		if ("USER".equals(parameterName)) return fUSER;
		if ("ROLEA".equals(parameterName)) return fROLEA;
		if ("ROLEB".equals(parameterName)) return fROLEB;
		return null;
	}	
	
	public Object getValueOfUSER(){
		 return fUSER;
	}
	public Object getValueOfROLEA(){
		 return fROLEA;
	}
	public Object getValueOfROLEB(){
		 return fROLEB;
	}	
	
	// setter methods
	/** 
	 * Sets the parameter with the given name to the given value. 
	 * @returns true if successful, false if parameter name is invalid. May also fail and return false if the value type is incompatible. 
	 */
	@Override
	public boolean set(String parameterName, Object newValue) {
		if ("USER".equals(parameterName)) {
			fUSER = newValue;
			return true;
		}
		if ("ROLEA".equals(parameterName)) {
			fROLEA = newValue;
			return true;
		}
		if ("ROLEB".equals(parameterName)) {
			fROLEB = newValue;
			return true;
		}
		return false;
	}
	
	public void setValueOfUSER(Object USER){
		 this.fUSER=USER;
	}
	public void setValueOfROLEA(Object ROLEA){
		 this.fROLEA=ROLEA;
	}
	public void setValueOfROLEB(Object ROLEB){
		 this.fROLEB=ROLEB;
	}

	// overridden prettyPrint(), hashCode(), equals() with Tuple-semantics
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (! (obj instanceof IPatternSignature))
			return false;
		IPatternSignature otherSig = (IPatternSignature) obj;
		if (!patternName().equals(otherSig.patternName()))
			return false;
		if (!DsodSignature.class.equals(obj.getClass()))
			return Arrays.deepEquals(toArray(), otherSig.toArray());
		DsodSignature other = (DsodSignature) obj;
		if (fUSER == null) {if (other.fUSER != null) return false;}
		else if (!fUSER.equals(other.fUSER)) return false;
		if (fROLEA == null) {if (other.fROLEA != null) return false;}
		else if (!fROLEA.equals(other.fROLEA)) return false;
		if (fROLEB == null) {if (other.fROLEB != null) return false;}
		else if (!fROLEB.equals(other.fROLEB)) return false;
		return true;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((fUSER == null) ? 0 : fUSER.hashCode());
		result = prime * result + ((fROLEA == null) ? 0 : fROLEA.hashCode());
		result = prime * result + ((fROLEB == null) ? 0 : fROLEB.hashCode());
		return result;
	}

	@Override
	public String prettyPrint() {
		StringBuilder result = new StringBuilder();
		result.append("\"USER\"=" + prettyPrintValue(fUSER));
		result.append(", \"ROLEA\"=" + prettyPrintValue(fROLEA));
		result.append(", \"ROLEB\"=" + prettyPrintValue(fROLEB));
		return result.toString();
	}

	// conversion and reflection
	/** Converts the signature to an array representation, with each pattern parameter at their respective position */
	@Override
	public Object[] toArray() {
		return new Object[] {fUSER, fROLEA, fROLEB};
	}
	
	/** Identifies the name of the pattern for which this is a signature. */
	@Override
	public String patternName() {
		return "policy.dsod";
	}
	
	/** Returns the list of symbolic parameter names. */
	@Override
	public String[] parameterNames() {
		return parameterNames;
	}
	private static String[] parameterNames = {"USER", "ROLEA", "ROLEB"};
	
	
}
