/*******************************************************************************
 * Pattern builder for pattern kevoree.channel
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.kevoree;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern kevoree.channel
 */
public class PatternBuilderForchannel implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("kevoree.channel".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("kevoree.channel");
		
		final Address<? extends Receiver> var_48 = buildable.patternCollector("kevoree.channel");
		final Stub<Address<? extends Supplier>> var_49 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_50 = EPackage.Registry.INSTANCE.getEPackage("http://kevoree/1.0").getEClassifier("Channel");
		final Stub<Address<? extends Supplier>> var_51 = buildable.unaryTypeStub(new FlatTuple(new Object[] {"CHA"}), var_50);
		final TupleMask var_52 = new TupleMask(new int[] {}, 0);
		final TupleMask var_53 = new TupleMask(new int[] {}, 1);
		final TupleMask var_54 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_55 = buildable.buildBetaNode(var_49, var_51, var_52, var_53, var_54, false);
		final TupleMask var_56 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_57 = buildable.buildTrimmer(var_55, var_56);
		buildable.buildConnection(var_57, var_48);
		return var_48;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("kevoree.channel".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("CHA", 0);

		}
		return posMapping;
	}
}
