/*******************************************************************************
 * Pattern builder for pattern kevoree.node
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.kevoree;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern kevoree.node
 */
public class PatternBuilderFornode implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("kevoree.node".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("kevoree.node");
		
		final Address<? extends Receiver> var_340 = buildable.patternCollector("kevoree.node");
		final Stub<Address<? extends Supplier>> var_341 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_342 = EPackage.Registry.INSTANCE.getEPackage("http://kevoree/1.0").getEClassifier("ContainerNode");
		final Stub<Address<? extends Supplier>> var_343 = buildable.unaryTypeStub(new FlatTuple(new Object[] {"N"}), var_342);
		final TupleMask var_344 = new TupleMask(new int[] {}, 0);
		final TupleMask var_345 = new TupleMask(new int[] {}, 1);
		final TupleMask var_346 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_347 = buildable.buildBetaNode(var_341, var_343, var_344, var_345, var_346, false);
		final TupleMask var_348 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_349 = buildable.buildTrimmer(var_347, var_348);
		buildable.buildConnection(var_349, var_340);
		return var_340;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("kevoree.node".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("N", 0);

		}
		return posMapping;
	}
}
