/*******************************************************************************
 * Pattern builder for pattern policy.operation
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.policy;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern policy.operation
 */
public class PatternBuilderForoperation implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("policy.operation".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("policy.operation");
		
		final Address<? extends Receiver> var_292 = buildable.patternCollector("policy.operation");
		final Stub<Address<? extends Supplier>> var_293 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_294 = EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("Operation");
		final Stub<Address<? extends Supplier>> var_295 = buildable.unaryTypeStub(new FlatTuple(new Object[] {"OP"}), var_294);
		final TupleMask var_296 = new TupleMask(new int[] {}, 0);
		final TupleMask var_297 = new TupleMask(new int[] {}, 1);
		final TupleMask var_298 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_299 = buildable.buildBetaNode(var_293, var_295, var_296, var_297, var_298, false);
		final TupleMask var_300 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_301 = buildable.buildTrimmer(var_299, var_300);
		buildable.buildConnection(var_301, var_292);
		return var_292;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("policy.operation".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("OP", 0);

		}
		return posMapping;
	}
}
