/*******************************************************************************
 * Pattern builder for pattern policy.userOperation
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.policy;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern policy.userOperation
 */
public class PatternBuilderForuserOperation implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("policy.userOperation".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("policy.userOperation");
		
		final Address<? extends Receiver> var_88 = buildable.patternCollector("policy.userOperation");
		final Stub<Address<? extends Supplier>> var_89 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_90 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("PolicyElement"))).getEStructuralFeature("name");
		final Stub<Address<? extends Supplier>> var_91 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"OPERATION", "OPERATIONNAME"}), var_90);
		final TupleMask var_92 = new TupleMask(new int[] {}, 0);
		final TupleMask var_93 = new TupleMask(new int[] {}, 2);
		final TupleMask var_94 = new TupleMask(new int[] {0, 1}, 2);
		final Stub<Address<? extends Supplier>> var_95 = buildable.buildBetaNode(var_89, var_91, var_92, var_93, var_94, false);
		final Stub<Address<? extends Supplier>> var_96 = buildable.buildInjectivityChecker(var_95, 0, new int[] {1});
		final Object var_97 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("Permission"))).getEStructuralFeature("operations");
		final Stub<Address<? extends Supplier>> var_98 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"PERMISSION", "OPERATION"}), var_97);
		final TupleMask var_99 = new TupleMask(new int[] {0}, 2);
		final TupleMask var_100 = new TupleMask(new int[] {1}, 2);
		final TupleMask var_101 = new TupleMask(new int[] {0}, 2);
		final Stub<Address<? extends Supplier>> var_102 = buildable.buildBetaNode(var_96, var_98, var_99, var_100, var_101, false);
		final Stub<Address<? extends Supplier>> var_103 = buildable.buildInjectivityChecker(var_102, 0, new int[] {2});
		final Stub<Address<? extends Supplier>> var_104 = buildable.buildInjectivityChecker(var_103, 1, new int[] {2});
		final Object var_105 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("Role"))).getEStructuralFeature("permissions");
		final Stub<Address<? extends Supplier>> var_106 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"ROLE", "PERMISSION"}), var_105);
		final TupleMask var_107 = new TupleMask(new int[] {2}, 3);
		final TupleMask var_108 = new TupleMask(new int[] {1}, 2);
		final TupleMask var_109 = new TupleMask(new int[] {0}, 2);
		final Stub<Address<? extends Supplier>> var_110 = buildable.buildBetaNode(var_104, var_106, var_107, var_108, var_109, false);
		final Stub<Address<? extends Supplier>> var_111 = buildable.buildInjectivityChecker(var_110, 0, new int[] {3});
		final Stub<Address<? extends Supplier>> var_112 = buildable.buildInjectivityChecker(var_111, 1, new int[] {3});
		final Stub<Address<? extends Supplier>> var_113 = buildable.buildInjectivityChecker(var_112, 2, new int[] {3});
		final Object var_114 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("User"))).getEStructuralFeature("roles");
		final Stub<Address<? extends Supplier>> var_115 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"USER", "ROLE"}), var_114);
		final TupleMask var_116 = new TupleMask(new int[] {3}, 4);
		final TupleMask var_117 = new TupleMask(new int[] {1}, 2);
		final TupleMask var_118 = new TupleMask(new int[] {0}, 2);
		final Stub<Address<? extends Supplier>> var_119 = buildable.buildBetaNode(var_113, var_115, var_116, var_117, var_118, false);
		final Stub<Address<? extends Supplier>> var_120 = buildable.buildInjectivityChecker(var_119, 0, new int[] {4});
		final Stub<Address<? extends Supplier>> var_121 = buildable.buildInjectivityChecker(var_120, 1, new int[] {4});
		final Stub<Address<? extends Supplier>> var_122 = buildable.buildInjectivityChecker(var_121, 2, new int[] {4});
		final Stub<Address<? extends Supplier>> var_123 = buildable.buildInjectivityChecker(var_122, 3, new int[] {4});
		final TupleMask var_124 = new TupleMask(new int[] {4, 1}, 5);
		final Stub<Address<? extends Supplier>> var_125 = buildable.buildTrimmer(var_123, var_124);
		buildable.buildConnection(var_125, var_88);
		return var_88;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("policy.userOperation".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("USER", 0);
			posMapping.put("OPERATIONNAME", 1);

		}
		return posMapping;
	}
}
