/*******************************************************************************
 * Pattern builder for pattern policy.userRoleRule
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.policy;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern policy.userRoleRule
 */
public class PatternBuilderForuserRoleRule implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("policy.userRoleRule".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("policy.userRoleRule");
		
		final Address<? extends Receiver> var_558 = buildable.patternCollector("policy.userRoleRule");
		final Stub<Address<? extends Supplier>> var_559 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_560 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("Role"))).getEStructuralFeature("permissions");
		final Stub<Address<? extends Supplier>> var_561 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"ROLE", "PERMISSION"}), var_560);
		final TupleMask var_562 = new TupleMask(new int[] {}, 0);
		final TupleMask var_563 = new TupleMask(new int[] {}, 2);
		final TupleMask var_564 = new TupleMask(new int[] {0, 1}, 2);
		final Stub<Address<? extends Supplier>> var_565 = buildable.buildBetaNode(var_559, var_561, var_562, var_563, var_564, false);
		final Stub<Address<? extends Supplier>> var_566 = buildable.buildInjectivityChecker(var_565, 1, new int[] {0});
		final Object var_567 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("User"))).getEStructuralFeature("roles");
		final Stub<Address<? extends Supplier>> var_568 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"USER", "ROLE"}), var_567);
		final TupleMask var_569 = new TupleMask(new int[] {0}, 2);
		final TupleMask var_570 = new TupleMask(new int[] {1}, 2);
		final TupleMask var_571 = new TupleMask(new int[] {0}, 2);
		final Stub<Address<? extends Supplier>> var_572 = buildable.buildBetaNode(var_566, var_568, var_569, var_570, var_571, false);
		final Stub<Address<? extends Supplier>> var_573 = buildable.buildInjectivityChecker(var_572, 1, new int[] {2});
		final Stub<Address<? extends Supplier>> var_574 = buildable.buildInjectivityChecker(var_573, 0, new int[] {2});
		final Object var_575 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("Permission"))).getEStructuralFeature("operations");
		final Stub<Address<? extends Supplier>> var_576 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"PERMISSION", "OPERATION"}), var_575);
		final TupleMask var_577 = new TupleMask(new int[] {1}, 3);
		final TupleMask var_578 = new TupleMask(new int[] {0}, 2);
		final TupleMask var_579 = new TupleMask(new int[] {1}, 2);
		final Stub<Address<? extends Supplier>> var_580 = buildable.buildBetaNode(var_574, var_576, var_577, var_578, var_579, false);
		final Stub<Address<? extends Supplier>> var_581 = buildable.buildInjectivityChecker(var_580, 3, new int[] {1});
		final Stub<Address<? extends Supplier>> var_582 = buildable.buildInjectivityChecker(var_581, 3, new int[] {0});
		final Stub<Address<? extends Supplier>> var_583 = buildable.buildInjectivityChecker(var_582, 3, new int[] {2});
		final Object var_584 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("Operation"))).getEStructuralFeature("objects");
		final Stub<Address<? extends Supplier>> var_585 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"OPERATION", "OBJECT"}), var_584);
		final TupleMask var_586 = new TupleMask(new int[] {3}, 4);
		final TupleMask var_587 = new TupleMask(new int[] {0}, 2);
		final TupleMask var_588 = new TupleMask(new int[] {1}, 2);
		final Stub<Address<? extends Supplier>> var_589 = buildable.buildBetaNode(var_583, var_585, var_586, var_587, var_588, false);
		final Stub<Address<? extends Supplier>> var_590 = buildable.buildInjectivityChecker(var_589, 4, new int[] {3});
		final Stub<Address<? extends Supplier>> var_591 = buildable.buildInjectivityChecker(var_590, 4, new int[] {1});
		final Stub<Address<? extends Supplier>> var_592 = buildable.buildInjectivityChecker(var_591, 4, new int[] {0});
		final Stub<Address<? extends Supplier>> var_593 = buildable.buildInjectivityChecker(var_592, 4, new int[] {2});
		final TupleMask var_594 = new TupleMask(new int[] {2, 0, 3, 4}, 5);
		final Stub<Address<? extends Supplier>> var_595 = buildable.buildTrimmer(var_593, var_594);
		buildable.buildConnection(var_595, var_558);
		return var_558;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("policy.userRoleRule".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("USER", 0);
			posMapping.put("ROLE", 1);
			posMapping.put("OPERATION", 2);
			posMapping.put("OBJECT", 3);

		}
		return posMapping;
	}
}
