/*******************************************************************************
 * Pattern builder for pattern policy.permission
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.policy;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern policy.permission
 */
public class PatternBuilderForpermission implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("policy.permission".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("policy.permission");
		
		final Address<? extends Receiver> var_310 = buildable.patternCollector("policy.permission");
		final Stub<Address<? extends Supplier>> var_311 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_312 = EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("Permission");
		final Stub<Address<? extends Supplier>> var_313 = buildable.unaryTypeStub(new FlatTuple(new Object[] {"P"}), var_312);
		final TupleMask var_314 = new TupleMask(new int[] {}, 0);
		final TupleMask var_315 = new TupleMask(new int[] {}, 1);
		final TupleMask var_316 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_317 = buildable.buildBetaNode(var_311, var_313, var_314, var_315, var_316, false);
		final TupleMask var_318 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_319 = buildable.buildTrimmer(var_317, var_318);
		buildable.buildConnection(var_319, var_310);
		return var_310;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("policy.permission".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("P", 0);

		}
		return posMapping;
	}
}
