/*******************************************************************************
 * Pattern builder for pattern policy.PermissionOperationAssignment
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.policy;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern policy.PermissionOperationAssignment
 */
public class PatternBuilderForPermissionOperationAssignment implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("policy.PermissionOperationAssignment".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("policy.PermissionOperationAssignment");
		
		final Address<? extends Receiver> var_547 = buildable.patternCollector("policy.PermissionOperationAssignment");
		final Stub<Address<? extends Supplier>> var_548 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_549 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("Permission"))).getEStructuralFeature("operations");
		final Stub<Address<? extends Supplier>> var_550 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"PERM", "OPE"}), var_549);
		final TupleMask var_551 = new TupleMask(new int[] {}, 0);
		final TupleMask var_552 = new TupleMask(new int[] {}, 2);
		final TupleMask var_553 = new TupleMask(new int[] {0, 1}, 2);
		final Stub<Address<? extends Supplier>> var_554 = buildable.buildBetaNode(var_548, var_550, var_551, var_552, var_553, false);
		final Stub<Address<? extends Supplier>> var_555 = buildable.buildInjectivityChecker(var_554, 1, new int[] {0});
		final TupleMask var_556 = new TupleMask(new int[] {0, 1}, 2);
		final Stub<Address<? extends Supplier>> var_557 = buildable.buildTrimmer(var_555, var_556);
		buildable.buildConnection(var_557, var_547);
		return var_547;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("policy.PermissionOperationAssignment".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("PERM", 0);
			posMapping.put("OPE", 1);

		}
		return posMapping;
	}
}
