/*******************************************************************************
 * Pattern builder for pattern policy.OperationObjectAssignment
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.policy;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern policy.OperationObjectAssignment
 */
public class PatternBuilderForOperationObjectAssignment implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("policy.OperationObjectAssignment".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("policy.OperationObjectAssignment");
		
		final Address<? extends Receiver> var_375 = buildable.patternCollector("policy.OperationObjectAssignment");
		final Stub<Address<? extends Supplier>> var_376 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_377 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("Permission"))).getEStructuralFeature("operations");
		final Stub<Address<? extends Supplier>> var_378 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"PERM", "OPE"}), var_377);
		final TupleMask var_379 = new TupleMask(new int[] {}, 0);
		final TupleMask var_380 = new TupleMask(new int[] {}, 2);
		final TupleMask var_381 = new TupleMask(new int[] {0, 1}, 2);
		final Stub<Address<? extends Supplier>> var_382 = buildable.buildBetaNode(var_376, var_378, var_379, var_380, var_381, false);
		final Stub<Address<? extends Supplier>> var_383 = buildable.buildInjectivityChecker(var_382, 1, new int[] {0});
		final Object var_384 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("Operation"))).getEStructuralFeature("objects");
		final Stub<Address<? extends Supplier>> var_385 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"OPE", "OBJ"}), var_384);
		final TupleMask var_386 = new TupleMask(new int[] {1}, 2);
		final TupleMask var_387 = new TupleMask(new int[] {0}, 2);
		final TupleMask var_388 = new TupleMask(new int[] {1}, 2);
		final Stub<Address<? extends Supplier>> var_389 = buildable.buildBetaNode(var_383, var_385, var_386, var_387, var_388, false);
		final Stub<Address<? extends Supplier>> var_390 = buildable.buildInjectivityChecker(var_389, 2, new int[] {1});
		final Stub<Address<? extends Supplier>> var_391 = buildable.buildInjectivityChecker(var_390, 2, new int[] {0});
		final TupleMask var_392 = new TupleMask(new int[] {0, 1, 2}, 3);
		final Stub<Address<? extends Supplier>> var_393 = buildable.buildTrimmer(var_391, var_392);
		buildable.buildConnection(var_393, var_375);
		return var_375;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("policy.OperationObjectAssignment".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("PERM", 0);
			posMapping.put("OPE", 1);
			posMapping.put("OBJ", 2);

		}
		return posMapping;
	}
}
