/*******************************************************************************
 * Pattern builder for pattern policy.RolePermissionAssignment
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.policy;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern policy.RolePermissionAssignment
 */
public class PatternBuilderForRolePermissionAssignment implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("policy.RolePermissionAssignment".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("policy.RolePermissionAssignment");
		
		final Address<? extends Receiver> var_632 = buildable.patternCollector("policy.RolePermissionAssignment");
		final Stub<Address<? extends Supplier>> var_633 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_634 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("Role"))).getEStructuralFeature("permissions");
		final Stub<Address<? extends Supplier>> var_635 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"ROLE", "PERM"}), var_634);
		final TupleMask var_636 = new TupleMask(new int[] {}, 0);
		final TupleMask var_637 = new TupleMask(new int[] {}, 2);
		final TupleMask var_638 = new TupleMask(new int[] {0, 1}, 2);
		final Stub<Address<? extends Supplier>> var_639 = buildable.buildBetaNode(var_633, var_635, var_636, var_637, var_638, false);
		final Stub<Address<? extends Supplier>> var_640 = buildable.buildInjectivityChecker(var_639, 1, new int[] {0});
		final TupleMask var_641 = new TupleMask(new int[] {0, 1}, 2);
		final Stub<Address<? extends Supplier>> var_642 = buildable.buildTrimmer(var_640, var_641);
		buildable.buildConnection(var_642, var_632);
		return var_632;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("policy.RolePermissionAssignment".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("ROLE", 0);
			posMapping.put("PERM", 1);

		}
		return posMapping;
	}
}
