/*******************************************************************************
 * Pattern builder for pattern policy.dsod
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.policy;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern policy.dsod
 */
public class PatternBuilderFordsod implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("policy.dsod".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("policy.dsod");
		
		final Address<? extends Receiver> var_350 = buildable.patternCollector("policy.dsod");
		final Stub<Address<? extends Supplier>> var_351 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_352 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("Role"))).getEStructuralFeature("dsod");
		final Stub<Address<? extends Supplier>> var_353 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"ROLEA", "ROLEB"}), var_352);
		final TupleMask var_354 = new TupleMask(new int[] {}, 0);
		final TupleMask var_355 = new TupleMask(new int[] {}, 2);
		final TupleMask var_356 = new TupleMask(new int[] {0, 1}, 2);
		final Stub<Address<? extends Supplier>> var_357 = buildable.buildBetaNode(var_351, var_353, var_354, var_355, var_356, false);
		final Stub<Address<? extends Supplier>> var_358 = buildable.buildInjectivityChecker(var_357, 0, new int[] {1});
		final Object var_359 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("User"))).getEStructuralFeature("roles");
		final Stub<Address<? extends Supplier>> var_360 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"USER", "ROLEA"}), var_359);
		final TupleMask var_361 = new TupleMask(new int[] {0}, 2);
		final TupleMask var_362 = new TupleMask(new int[] {1}, 2);
		final TupleMask var_363 = new TupleMask(new int[] {0}, 2);
		final Stub<Address<? extends Supplier>> var_364 = buildable.buildBetaNode(var_358, var_360, var_361, var_362, var_363, false);
		final Stub<Address<? extends Supplier>> var_365 = buildable.buildInjectivityChecker(var_364, 0, new int[] {2});
		final Stub<Address<? extends Supplier>> var_366 = buildable.buildInjectivityChecker(var_365, 1, new int[] {2});
		final Object var_367 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("User"))).getEStructuralFeature("roles");
		final Stub<Address<? extends Supplier>> var_368 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"USER", "ROLEB"}), var_367);
		final TupleMask var_369 = new TupleMask(new int[] {2, 1}, 3);
		final TupleMask var_370 = new TupleMask(new int[] {0, 1}, 2);
		final TupleMask var_371 = new TupleMask(new int[] {}, 2);
		final Stub<Address<? extends Supplier>> var_372 = buildable.buildBetaNode(var_366, var_368, var_369, var_370, var_371, false);
		final TupleMask var_373 = new TupleMask(new int[] {2, 0, 1}, 3);
		final Stub<Address<? extends Supplier>> var_374 = buildable.buildTrimmer(var_372, var_373);
		buildable.buildConnection(var_374, var_350);
		return var_350;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("policy.dsod".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("USER", 0);
			posMapping.put("ROLEA", 1);
			posMapping.put("ROLEB", 2);

		}
		return posMapping;
	}
}
