/*******************************************************************************
 * Pattern builder for pattern policy.user
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.policy;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern policy.user
 */
public class PatternBuilderForuser implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("policy.user".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("policy.user");
		
		final Address<? extends Receiver> var_87 = buildable.patternCollector("policy.user");
		final Stub<Address<? extends Supplier>> var_88 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_89 = EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("User");
		final Stub<Address<? extends Supplier>> var_90 = buildable.unaryTypeStub(new FlatTuple(new Object[] {"U"}), var_89);
		final TupleMask var_91 = new TupleMask(new int[] {}, 0);
		final TupleMask var_92 = new TupleMask(new int[] {}, 1);
		final TupleMask var_93 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_94 = buildable.buildBetaNode(var_88, var_90, var_91, var_92, var_93, false);
		final TupleMask var_95 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_96 = buildable.buildTrimmer(var_94, var_95);
		buildable.buildConnection(var_96, var_87);
		return var_87;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("policy.user".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("U", 0);

		}
		return posMapping;
	}
}
