/*******************************************************************************
 * EMF Specific API of the kevoree.connection pattern
 * Generated by EMF-IncQuery
 *******************************************************************************/

package patternmatchers.kevoree;

import java.util.Collection;

import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseGeneratedMatcher;
import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseMatcherFactory;
import org.eclipse.viatra2.emf.incquery.runtime.api.IPatternSignature;
import org.eclipse.viatra2.emf.incquery.runtime.api.IMatcherFactory;
import org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher;
import org.eclipse.viatra2.emf.incquery.runtime.exception.IncQueryRuntimeException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.ReteEngine;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;

import signatures.kevoree.ConnectionSignature;

/**
 * Generated domain-specific pattern matcher API of of the kevoree.connection pattern.
 * Please instantiate using the static field FACTORY.
 */
@SuppressWarnings("unused")
public class ConnectionMatcher extends BaseGeneratedMatcher<ConnectionSignature> implements IncQueryMatcher<ConnectionSignature>{

	public final static IMatcherFactory<ConnectionSignature,ConnectionMatcher> FACTORY = new Factory();
	public static class Factory extends BaseMatcherFactory<ConnectionSignature,ConnectionMatcher> {
			@Override
			public ConnectionMatcher instantiate(ReteEngine<String> reteEngine) throws IncQueryRuntimeException {
				return new ConnectionMatcher(reteEngine);
			}
			@Override
			public String getPatternName() {
				return "kevoree.connection";
			}
		} 
			
	
	/** 
	 * Returns the set of all pattern matches given some fixed parameters.
	 * @param N the fixed value of pattern parameter N, or null if not bound.
	 * @param C the fixed value of pattern parameter C, or null if not bound.
	 * @param P the fixed value of pattern parameter P, or null if not bound.
	 * @param B the fixed value of pattern parameter B, or null if not bound.
	 * @return matches represented as an array containing the values of each parameter.
	 */
	public Collection<Object[]> getAllMatchesAsArray(Object N, Object C, Object P, Object B) {
		return getAllMatchesAsArray(new Object[] {N, C, P, B});
	}
	
	/** 
	 * Returns the set of all pattern matches given some fixed parameters.
	 * @param N the fixed value of pattern parameter N, or null if not bound.
	 * @param C the fixed value of pattern parameter C, or null if not bound.
	 * @param P the fixed value of pattern parameter P, or null if not bound.
	 * @param B the fixed value of pattern parameter B, or null if not bound.
	 * @return matches represented as a ConnectionSignature object.
	 */
	public Collection<ConnectionSignature> getAllMatchesAsSignature(Object N, Object C, Object P, Object B) {
		return getAllMatchesAsSignature(new Object[] {N, C, P, B});
	}

	/** 
	 * Returns an arbitrary pattern match given some fixed parameters.
	 * Neither determinism nor randomness of selection is guaranteed.
	 * @param N the fixed value of pattern parameter N, or null if not bound.
	 * @param C the fixed value of pattern parameter C, or null if not bound.
	 * @param P the fixed value of pattern parameter P, or null if not bound.
	 * @param B the fixed value of pattern parameter B, or null if not bound.
	 * @return a match represented as an array containing the values of each parameter, or null if no match is found.
	 */
	public Object[] getOneMatchAsArray(Object N, Object C, Object P, Object B) {
		return getOneMatchAsArray(new Object[] {N, C, P, B});
	}
	
	/** 
	 * Returns an arbitrary pattern match given some fixed parameters.
	 * Neither determinism nor randomness of selection is guaranteed.
	 * @param N the fixed value of pattern parameter N, or null if not bound.
	 * @param C the fixed value of pattern parameter C, or null if not bound.
	 * @param P the fixed value of pattern parameter P, or null if not bound.
	 * @param B the fixed value of pattern parameter B, or null if not bound.
	 * @return a match represented as a ConnectionSignature object, or null if no match is found.
	 */
	public ConnectionSignature getOneMatchAsSignature(Object N, Object C, Object P, Object B) {
		return getOneMatchAsSignature(new Object[] {N, C, P, B});
	}
	
	/**
	 * Indicates whether the given combination of specified pattern parameters constitute a valid pattern match,
	 * 	under any possible substitution of the unspecified parameters.
	 * @param N the fixed value of pattern parameter N, or null if not bound.
	 * @param C the fixed value of pattern parameter C, or null if not bound.
	 * @param P the fixed value of pattern parameter P, or null if not bound.
	 * @param B the fixed value of pattern parameter B, or null if not bound.
	 * @return true if the input is a valid (partial) match of the pattern.
	 */
	public boolean hasMatch(Object N, Object C, Object P, Object B) {
		return hasMatch(new Object[] {N, C, P, B});
	}
	
	/** 
	 * Returns the number of all pattern matches given some fixed parameters.
	 * @param N the fixed value of pattern parameter N, or null if not bound.
	 * @param C the fixed value of pattern parameter C, or null if not bound.
	 * @param P the fixed value of pattern parameter P, or null if not bound.
	 * @param B the fixed value of pattern parameter B, or null if not bound.
	 * @return the number of pattern matches found.
	 */	
	public int countMatches(Object N, Object C, Object P, Object B) {
		return countMatches(new Object[] {N, C, P, B});
	}
	


	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#getPatternName()
	 */
	@Override
	public String getPatternName() {
		return "kevoree.connection";
	}

	private static final String[] paramNames = new String[] {"N", "C", "P", "B"};
	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#getParameterNames()
	 */
	@Override
	public String[] getParameterNames() {
		return paramNames;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseGeneratedMatcher#tupleToSignature(org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple)
	 */
	@Override
	protected ConnectionSignature tupleToSignature(Tuple t) {
		return new ConnectionSignature(t.get(0), t.get(1), t.get(2), t.get(3));
	}
	
	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#arrayToSignature(java.lang.Object[])
	 */
	@Override
	public ConnectionSignature arrayToSignature(Object[] signature) {
		return new ConnectionSignature(signature[0], signature[1], signature[2], signature[3]);
	}	
	
	private ConnectionMatcher(ReteEngine<String> engine) throws IncQueryRuntimeException {
		super(engine, "kevoree.connection");
	}
		
}
