/*******************************************************************************
 * EMF Specific API of the kevoree.nodeComponent pattern
 * Generated by EMF-IncQuery
 *******************************************************************************/

package patternmatchers.kevoree;

import java.util.Collection;

import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseGeneratedMatcher;
import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseMatcherFactory;
import org.eclipse.viatra2.emf.incquery.runtime.api.IPatternSignature;
import org.eclipse.viatra2.emf.incquery.runtime.api.IMatcherFactory;
import org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher;
import org.eclipse.viatra2.emf.incquery.runtime.exception.IncQueryRuntimeException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.ReteEngine;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;

import signatures.kevoree.NodeComponentSignature;

/**
 * Generated domain-specific pattern matcher API of of the kevoree.nodeComponent pattern.
 * Please instantiate using the static field FACTORY.
 */
@SuppressWarnings("unused")
public class NodeComponentMatcher extends BaseGeneratedMatcher<NodeComponentSignature> implements IncQueryMatcher<NodeComponentSignature>{

	public final static IMatcherFactory<NodeComponentSignature,NodeComponentMatcher> FACTORY = new Factory();
	public static class Factory extends BaseMatcherFactory<NodeComponentSignature,NodeComponentMatcher> {
			@Override
			public NodeComponentMatcher instantiate(ReteEngine<String> reteEngine) throws IncQueryRuntimeException {
				return new NodeComponentMatcher(reteEngine);
			}
			@Override
			public String getPatternName() {
				return "kevoree.nodeComponent";
			}
		} 
			
	
	/** 
	 * Returns the set of all pattern matches given some fixed parameters.
	 * @param N the fixed value of pattern parameter N, or null if not bound.
	 * @param C the fixed value of pattern parameter C, or null if not bound.
	 * @return matches represented as an array containing the values of each parameter.
	 */
	public Collection<Object[]> getAllMatchesAsArray(Object N, Object C) {
		return getAllMatchesAsArray(new Object[] {N, C});
	}
	
	/** 
	 * Returns the set of all pattern matches given some fixed parameters.
	 * @param N the fixed value of pattern parameter N, or null if not bound.
	 * @param C the fixed value of pattern parameter C, or null if not bound.
	 * @return matches represented as a NodeComponentSignature object.
	 */
	public Collection<NodeComponentSignature> getAllMatchesAsSignature(Object N, Object C) {
		return getAllMatchesAsSignature(new Object[] {N, C});
	}

	/** 
	 * Returns an arbitrary pattern match given some fixed parameters.
	 * Neither determinism nor randomness of selection is guaranteed.
	 * @param N the fixed value of pattern parameter N, or null if not bound.
	 * @param C the fixed value of pattern parameter C, or null if not bound.
	 * @return a match represented as an array containing the values of each parameter, or null if no match is found.
	 */
	public Object[] getOneMatchAsArray(Object N, Object C) {
		return getOneMatchAsArray(new Object[] {N, C});
	}
	
	/** 
	 * Returns an arbitrary pattern match given some fixed parameters.
	 * Neither determinism nor randomness of selection is guaranteed.
	 * @param N the fixed value of pattern parameter N, or null if not bound.
	 * @param C the fixed value of pattern parameter C, or null if not bound.
	 * @return a match represented as a NodeComponentSignature object, or null if no match is found.
	 */
	public NodeComponentSignature getOneMatchAsSignature(Object N, Object C) {
		return getOneMatchAsSignature(new Object[] {N, C});
	}
	
	/**
	 * Indicates whether the given combination of specified pattern parameters constitute a valid pattern match,
	 * 	under any possible substitution of the unspecified parameters.
	 * @param N the fixed value of pattern parameter N, or null if not bound.
	 * @param C the fixed value of pattern parameter C, or null if not bound.
	 * @return true if the input is a valid (partial) match of the pattern.
	 */
	public boolean hasMatch(Object N, Object C) {
		return hasMatch(new Object[] {N, C});
	}
	
	/** 
	 * Returns the number of all pattern matches given some fixed parameters.
	 * @param N the fixed value of pattern parameter N, or null if not bound.
	 * @param C the fixed value of pattern parameter C, or null if not bound.
	 * @return the number of pattern matches found.
	 */	
	public int countMatches(Object N, Object C) {
		return countMatches(new Object[] {N, C});
	}
	


	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#getPatternName()
	 */
	@Override
	public String getPatternName() {
		return "kevoree.nodeComponent";
	}

	private static final String[] paramNames = new String[] {"N", "C"};
	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#getParameterNames()
	 */
	@Override
	public String[] getParameterNames() {
		return paramNames;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseGeneratedMatcher#tupleToSignature(org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple)
	 */
	@Override
	protected NodeComponentSignature tupleToSignature(Tuple t) {
		return new NodeComponentSignature(t.get(0), t.get(1));
	}
	
	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#arrayToSignature(java.lang.Object[])
	 */
	@Override
	public NodeComponentSignature arrayToSignature(Object[] signature) {
		return new NodeComponentSignature(signature[0], signature[1]);
	}	
	
	private NodeComponentMatcher(ReteEngine<String> engine) throws IncQueryRuntimeException {
		super(engine, "kevoree.nodeComponent");
	}
		
}
