/*******************************************************************************
 * EMF Specific API of the kevoree.threeBuyers pattern
 * Generated by EMF-IncQuery
 *******************************************************************************/

package patternmatchers.kevoree;

import java.util.Collection;

import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseGeneratedMatcher;
import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseMatcherFactory;
import org.eclipse.viatra2.emf.incquery.runtime.api.IPatternSignature;
import org.eclipse.viatra2.emf.incquery.runtime.api.IMatcherFactory;
import org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher;
import org.eclipse.viatra2.emf.incquery.runtime.exception.IncQueryRuntimeException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.ReteEngine;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;

import signatures.kevoree.ThreeBuyersSignature;

/**
 * Generated domain-specific pattern matcher API of of the kevoree.threeBuyers pattern.
 * Please instantiate using the static field FACTORY.
 */
@SuppressWarnings("unused")
public class ThreeBuyersMatcher extends BaseGeneratedMatcher<ThreeBuyersSignature> implements IncQueryMatcher<ThreeBuyersSignature>{

	public final static IMatcherFactory<ThreeBuyersSignature,ThreeBuyersMatcher> FACTORY = new Factory();
	public static class Factory extends BaseMatcherFactory<ThreeBuyersSignature,ThreeBuyersMatcher> {
			@Override
			public ThreeBuyersMatcher instantiate(ReteEngine<String> reteEngine) throws IncQueryRuntimeException {
				return new ThreeBuyersMatcher(reteEngine);
			}
			@Override
			public String getPatternName() {
				return "kevoree.threeBuyers";
			}
		} 
			
	
	/** 
	 * Returns the set of all pattern matches given some fixed parameters.
	 * @param N1 the fixed value of pattern parameter N1, or null if not bound.
	 * @param C1 the fixed value of pattern parameter C1, or null if not bound.
	 * @param N2 the fixed value of pattern parameter N2, or null if not bound.
	 * @param C2 the fixed value of pattern parameter C2, or null if not bound.
	 * @param N3 the fixed value of pattern parameter N3, or null if not bound.
	 * @param C3 the fixed value of pattern parameter C3, or null if not bound.
	 * @return matches represented as an array containing the values of each parameter.
	 */
	public Collection<Object[]> getAllMatchesAsArray(Object N1, Object C1, Object N2, Object C2, Object N3, Object C3) {
		return getAllMatchesAsArray(new Object[] {N1, C1, N2, C2, N3, C3});
	}
	
	/** 
	 * Returns the set of all pattern matches given some fixed parameters.
	 * @param N1 the fixed value of pattern parameter N1, or null if not bound.
	 * @param C1 the fixed value of pattern parameter C1, or null if not bound.
	 * @param N2 the fixed value of pattern parameter N2, or null if not bound.
	 * @param C2 the fixed value of pattern parameter C2, or null if not bound.
	 * @param N3 the fixed value of pattern parameter N3, or null if not bound.
	 * @param C3 the fixed value of pattern parameter C3, or null if not bound.
	 * @return matches represented as a ThreeBuyersSignature object.
	 */
	public Collection<ThreeBuyersSignature> getAllMatchesAsSignature(Object N1, Object C1, Object N2, Object C2, Object N3, Object C3) {
		return getAllMatchesAsSignature(new Object[] {N1, C1, N2, C2, N3, C3});
	}

	/** 
	 * Returns an arbitrary pattern match given some fixed parameters.
	 * Neither determinism nor randomness of selection is guaranteed.
	 * @param N1 the fixed value of pattern parameter N1, or null if not bound.
	 * @param C1 the fixed value of pattern parameter C1, or null if not bound.
	 * @param N2 the fixed value of pattern parameter N2, or null if not bound.
	 * @param C2 the fixed value of pattern parameter C2, or null if not bound.
	 * @param N3 the fixed value of pattern parameter N3, or null if not bound.
	 * @param C3 the fixed value of pattern parameter C3, or null if not bound.
	 * @return a match represented as an array containing the values of each parameter, or null if no match is found.
	 */
	public Object[] getOneMatchAsArray(Object N1, Object C1, Object N2, Object C2, Object N3, Object C3) {
		return getOneMatchAsArray(new Object[] {N1, C1, N2, C2, N3, C3});
	}
	
	/** 
	 * Returns an arbitrary pattern match given some fixed parameters.
	 * Neither determinism nor randomness of selection is guaranteed.
	 * @param N1 the fixed value of pattern parameter N1, or null if not bound.
	 * @param C1 the fixed value of pattern parameter C1, or null if not bound.
	 * @param N2 the fixed value of pattern parameter N2, or null if not bound.
	 * @param C2 the fixed value of pattern parameter C2, or null if not bound.
	 * @param N3 the fixed value of pattern parameter N3, or null if not bound.
	 * @param C3 the fixed value of pattern parameter C3, or null if not bound.
	 * @return a match represented as a ThreeBuyersSignature object, or null if no match is found.
	 */
	public ThreeBuyersSignature getOneMatchAsSignature(Object N1, Object C1, Object N2, Object C2, Object N3, Object C3) {
		return getOneMatchAsSignature(new Object[] {N1, C1, N2, C2, N3, C3});
	}
	
	/**
	 * Indicates whether the given combination of specified pattern parameters constitute a valid pattern match,
	 * 	under any possible substitution of the unspecified parameters.
	 * @param N1 the fixed value of pattern parameter N1, or null if not bound.
	 * @param C1 the fixed value of pattern parameter C1, or null if not bound.
	 * @param N2 the fixed value of pattern parameter N2, or null if not bound.
	 * @param C2 the fixed value of pattern parameter C2, or null if not bound.
	 * @param N3 the fixed value of pattern parameter N3, or null if not bound.
	 * @param C3 the fixed value of pattern parameter C3, or null if not bound.
	 * @return true if the input is a valid (partial) match of the pattern.
	 */
	public boolean hasMatch(Object N1, Object C1, Object N2, Object C2, Object N3, Object C3) {
		return hasMatch(new Object[] {N1, C1, N2, C2, N3, C3});
	}
	
	/** 
	 * Returns the number of all pattern matches given some fixed parameters.
	 * @param N1 the fixed value of pattern parameter N1, or null if not bound.
	 * @param C1 the fixed value of pattern parameter C1, or null if not bound.
	 * @param N2 the fixed value of pattern parameter N2, or null if not bound.
	 * @param C2 the fixed value of pattern parameter C2, or null if not bound.
	 * @param N3 the fixed value of pattern parameter N3, or null if not bound.
	 * @param C3 the fixed value of pattern parameter C3, or null if not bound.
	 * @return the number of pattern matches found.
	 */	
	public int countMatches(Object N1, Object C1, Object N2, Object C2, Object N3, Object C3) {
		return countMatches(new Object[] {N1, C1, N2, C2, N3, C3});
	}
	


	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#getPatternName()
	 */
	@Override
	public String getPatternName() {
		return "kevoree.threeBuyers";
	}

	private static final String[] paramNames = new String[] {"N1", "C1", "N2", "C2", "N3", "C3"};
	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#getParameterNames()
	 */
	@Override
	public String[] getParameterNames() {
		return paramNames;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseGeneratedMatcher#tupleToSignature(org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple)
	 */
	@Override
	protected ThreeBuyersSignature tupleToSignature(Tuple t) {
		return new ThreeBuyersSignature(t.get(0), t.get(1), t.get(2), t.get(3), t.get(4), t.get(5));
	}
	
	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#arrayToSignature(java.lang.Object[])
	 */
	@Override
	public ThreeBuyersSignature arrayToSignature(Object[] signature) {
		return new ThreeBuyersSignature(signature[0], signature[1], signature[2], signature[3], signature[4], signature[5]);
	}	
	
	private ThreeBuyersMatcher(ReteEngine<String> engine) throws IncQueryRuntimeException {
		super(engine, "kevoree.threeBuyers");
	}
		
}
