/*******************************************************************************
 * Pattern signature of the kevoree.threeBuyers pattern
 * Generated by EMF-IncQuery
 *******************************************************************************/

package signatures.kevoree;

import java.util.Arrays;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.viatra2.emf.incquery.runtime.api.IPatternSignature;
import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BasePatternSignature;

/**
 * Pattern-specific signature object of the kevoree.threeBuyers pattern.
 * Class fields correspond to parameters of the pattern. Fields with value null are considered unassigned.
 * Each instance is a (possibly partial) substitution of pattern parameters, 
 * usable e.g. to represent a match of the pattern in the result of a query, 
 * or to specify the bound (fixed) input parameters when issuing a query.
 */
@SuppressWarnings("unused")
public final class ThreeBuyersSignature extends BasePatternSignature implements IPatternSignature {

	// constructor
	public ThreeBuyersSignature(Object N1, Object C1, Object N2, Object C2, Object N3, Object C3) {
		this.fN1 = N1;
		this.fC1 = C1;
		this.fN2 = N2;
		this.fC2 = C2;
		this.fN3 = N3;
		this.fC3 = C3;	
	}

	//private attributes
	private Object fN1;
	private Object fC1;
	private Object fN2;
	private Object fC2;
	private Object fN3;
	private Object fC3;
	
	// getter methods
	/** Returns the value of the parameter with the given name, or null if name is invalid. */
	@Override
	public Object get(String parameterName) {
		if ("N1".equals(parameterName)) return fN1;
		if ("C1".equals(parameterName)) return fC1;
		if ("N2".equals(parameterName)) return fN2;
		if ("C2".equals(parameterName)) return fC2;
		if ("N3".equals(parameterName)) return fN3;
		if ("C3".equals(parameterName)) return fC3;
		return null;
	}	
	
	public Object getValueOfN1(){
		 return fN1;
	}
	public Object getValueOfC1(){
		 return fC1;
	}
	public Object getValueOfN2(){
		 return fN2;
	}
	public Object getValueOfC2(){
		 return fC2;
	}
	public Object getValueOfN3(){
		 return fN3;
	}
	public Object getValueOfC3(){
		 return fC3;
	}	
	
	// setter methods
	/** 
	 * Sets the parameter with the given name to the given value. 
	 * @returns true if successful, false if parameter name is invalid. May also fail and return false if the value type is incompatible. 
	 */
	@Override
	public boolean set(String parameterName, Object newValue) {
		if ("N1".equals(parameterName)) {
			fN1 = newValue;
			return true;
		}
		if ("C1".equals(parameterName)) {
			fC1 = newValue;
			return true;
		}
		if ("N2".equals(parameterName)) {
			fN2 = newValue;
			return true;
		}
		if ("C2".equals(parameterName)) {
			fC2 = newValue;
			return true;
		}
		if ("N3".equals(parameterName)) {
			fN3 = newValue;
			return true;
		}
		if ("C3".equals(parameterName)) {
			fC3 = newValue;
			return true;
		}
		return false;
	}
	
	public void setValueOfN1(Object N1){
		 this.fN1=N1;
	}
	public void setValueOfC1(Object C1){
		 this.fC1=C1;
	}
	public void setValueOfN2(Object N2){
		 this.fN2=N2;
	}
	public void setValueOfC2(Object C2){
		 this.fC2=C2;
	}
	public void setValueOfN3(Object N3){
		 this.fN3=N3;
	}
	public void setValueOfC3(Object C3){
		 this.fC3=C3;
	}

	// overridden prettyPrint(), hashCode(), equals() with Tuple-semantics
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (! (obj instanceof IPatternSignature))
			return false;
		IPatternSignature otherSig = (IPatternSignature) obj;
		if (!patternName().equals(otherSig.patternName()))
			return false;
		if (!ThreeBuyersSignature.class.equals(obj.getClass()))
			return Arrays.deepEquals(toArray(), otherSig.toArray());
		ThreeBuyersSignature other = (ThreeBuyersSignature) obj;
		if (fN1 == null) {if (other.fN1 != null) return false;}
		else if (!fN1.equals(other.fN1)) return false;
		if (fC1 == null) {if (other.fC1 != null) return false;}
		else if (!fC1.equals(other.fC1)) return false;
		if (fN2 == null) {if (other.fN2 != null) return false;}
		else if (!fN2.equals(other.fN2)) return false;
		if (fC2 == null) {if (other.fC2 != null) return false;}
		else if (!fC2.equals(other.fC2)) return false;
		if (fN3 == null) {if (other.fN3 != null) return false;}
		else if (!fN3.equals(other.fN3)) return false;
		if (fC3 == null) {if (other.fC3 != null) return false;}
		else if (!fC3.equals(other.fC3)) return false;
		return true;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((fN1 == null) ? 0 : fN1.hashCode());
		result = prime * result + ((fC1 == null) ? 0 : fC1.hashCode());
		result = prime * result + ((fN2 == null) ? 0 : fN2.hashCode());
		result = prime * result + ((fC2 == null) ? 0 : fC2.hashCode());
		result = prime * result + ((fN3 == null) ? 0 : fN3.hashCode());
		result = prime * result + ((fC3 == null) ? 0 : fC3.hashCode());
		return result;
	}

	@Override
	public String prettyPrint() {
		StringBuilder result = new StringBuilder();
		result.append("\"N1\"=" + prettyPrintValue(fN1));
		result.append(", \"C1\"=" + prettyPrintValue(fC1));
		result.append(", \"N2\"=" + prettyPrintValue(fN2));
		result.append(", \"C2\"=" + prettyPrintValue(fC2));
		result.append(", \"N3\"=" + prettyPrintValue(fN3));
		result.append(", \"C3\"=" + prettyPrintValue(fC3));
		return result.toString();
	}

	// conversion and reflection
	/** Converts the signature to an array representation, with each pattern parameter at their respective position */
	@Override
	public Object[] toArray() {
		return new Object[] {fN1, fC1, fN2, fC2, fN3, fC3};
	}
	
	/** Identifies the name of the pattern for which this is a signature. */
	@Override
	public String patternName() {
		return "kevoree.threeBuyers";
	}
	
	/** Returns the list of symbolic parameter names. */
	@Override
	public String[] parameterNames() {
		return parameterNames;
	}
	private static String[] parameterNames = {"N1", "C1", "N2", "C2", "N3", "C3"};
	
	
}
